name: CMake Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        compiler: [gcc, clang]
    steps:
    - uses: actions/checkout@v4

    - name: Build all
      run: |
        cmake -B build -S .
        cmake --build build
